logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[acme]
email = "root@mail.doma.in"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
OnHostRule = true

[[acme.domains]]
  main = "mail.your.doma.in"
  sans = ["web.mail.your.doma.in", "smtp.mail.doma.in", "imap.mail.doma.in"]

[acme.httpChallenge]
entryPoint = "http"
